#pragma once
#include <boost/asio.hpp>
#include <boost/asio/deadline_timer.hpp>
#include <cstdio>
#include <thread>
#include <atomic>
#include <memory>
#include <iostream>
#include <sstream>
#include <mutex>
#include <string>
#include <cstring>
#include <regex>
#include <functional>
#include <mutex>
#include <future>
#include <time.h>
#include <Windows.h>
#include <vector>
#include <ctime>
#include <chrono>
#include <cstdlib>
#include <list>